#!/bin/sh

set -e

bundle exec jekyll build
bundle exec htmlproofer ./_site --check-html --url-ignore "/linkedin.com/,/scholar.google.com/,/fonts.googleapis.com/,/fonts.gstatic.com/"
bundle exec rubocop -D --config .rubocop.yml
bundle exec script/validate-html
gem build jekyll-theme-minimal.gemspec
